apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-app
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
    params:
      - name: pathToContext
        type: string
        default: /workspace/docker-source
      - name: targetNamespace
        type: string
        default: phonebook
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;docker-registry.default.svc:5000/phonebook/myphonebook_ui:0.4;docker-registry.default.svc:5000/myphonebook/myphonebook_ui:latest;g"
        - "${inputs.params.pathToContext}/kubernetes/ui_dep.yml"
    - name: oc-dep
      image: quay.io/openshift/origin-cli:latest
      env:
        - name: REG_PWD
          valueFrom:
            secretKeyRef:
              name: myphonebook-tekton-deployer-secret
              key: token
      command: ["/bin/bash", "-c"]
      args:
        - oc apply -f ${inputs.params.pathToContext}/kubernetes/ui_dep.yml --token=$REG_PWD -n ${inputs.params.targetNamespace}