apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: myphonebook-ui-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: http://github.com/jtarte/myphonebook_ui.git 
