apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: deploy-pipeline-run
spec:
  pipelineRef:
    name: deploy-pipeline
  resources:
    - name: docker-source
      resourceRef:
        name: myphonebook-ui-git
    - name: image-container
      resourceRef:
        name: myphonebookui-image
  params:
    - name: targetNamespace
      value: myphonebook