apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  resources:
    - name: docker-source
      type: git
    - name: image-container
      type: image
  params:
    - name: pathToContext
      description: The path to the build context
      default: /workspace/docker-source
    - name: targetNamespace
      description: the name of target namespace where the deployment is done 
      default: phonebook
  tasks:
  - name: deploy-cm-to-cluster
    taskRef:
      name: ui-deploy-cm
    params:
      - name: pathToContext
        value: "$(params.pathToContext)"
      - name: targetNamespace
        value: "$(params.targetNamespace)"
    resources:
      inputs:
        - name: docker-source
          resource: docker-source
  - name: deploy-app-to-cluster
    taskRef:
      name: deploy-app
    runAfter:
      - deploy-cm-to-cluster
    params:
      - name: pathToContext
        value: "$(params.pathToContext)"
      - name: targetNamespace
        value: "$(params.targetNamespace)"
    resources:
      inputs:
        - name: docker-source
          resource: docker-source
        - name: image-container
          resource: image-container
  - name: expose-app-to-cluster
    taskRef:
      name: expose-app
    runAfter:
      - deploy-app-to-cluster
    params:
      - name: pathToContext
        value: "$(params.pathToContext)"
      - name: targetNamespace
        value: "$(params.targetNamespace)"
    resources:
      inputs:
        - name: docker-source
          resource: docker-source